// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamPiZAZCPW211TeamProject.Database;

#nullable disable

namespace TeamPiZAZCPW211TeamProject.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    [Migration("20260817033314_AddedNewStudioSeedData")]
    partial class AddedNewStudioSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeGenre", b =>
                {
                    b.Property<int>("AnimesId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("AnimesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("AnimeGenre");
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<int?>("StudioId")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("Animes");
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Anime with intense action sequences and battles.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Anime that follows characters on exciting journeys and quests.",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Anime that focuses on humor and comedic situations.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Anime that explores emotional and dramatic storylines.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Anime set in fantastical worlds with magical elements.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Anime that aims to scare or unsettle the audience.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Anime that focuses on romantic relationships and love stories.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Anime that explores futuristic or scientific concepts.",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Anime that depicts everyday life and experiences of characters.",
                            Name = "Slice of Life"
                        });
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A renowned Japanese animation studio.",
                            Name = "Studio Ghibli"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A Japanese animation studio known for its high-quality productions.",
                            Name = "Madhouse"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A Japanese animation studio known for its diverse range of anime series.",
                            Name = "Bones"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A Japanese animation studio known for its detailed animation and character-driven stories.",
                            Name = "Kyoto Animation"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A Japanese animation studio known for its visually stunning anime adaptations.",
                            Name = "Ufotable"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A Japanese animation studio known for its mecha and science fiction anime.",
                            Name = "Sunrise"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A Japanese animation studio known for its creative and innovative approach to anime production.",
                            Name = "Wit Studio"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A Japanese animation studio known for its high-quality productions and attention to detail.",
                            Name = "Studio Deen"
                        });
                });

            modelBuilder.Entity("AnimeGenre", b =>
                {
                    b.HasOne("TeamPiZAZCPW211TeamProject.Models.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamPiZAZCPW211TeamProject.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Anime", b =>
                {
                    b.HasOne("TeamPiZAZCPW211TeamProject.Models.Studio", "Studio")
                        .WithMany("Animes")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Studio", b =>
                {
                    b.Navigation("Animes");
                });
#pragma warning restore 612, 618
        }
    }
}
