// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamPiZAZCPW211TeamProject.Database;

#nullable disable

namespace TeamPiZAZCPW211TeamProject.Migrations
{
    [DbContext(typeof(AnimeDbContext))]
    [Migration("20260824191535_AnimeSeedData")]
    partial class AnimeSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnimeGenre", b =>
                {
                    b.Property<int>("AnimesId")
                        .HasColumnType("int");

                    b.Property<int>("GenresId")
                        .HasColumnType("int");

                    b.HasKey("AnimesId", "GenresId");

                    b.HasIndex("GenresId");

                    b.ToTable("AnimeGenre");
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Anime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Episodes")
                        .HasColumnType("int");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<int?>("StudioId")
                        .HasColumnType("int");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TvRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudioId");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            Episodes = 366,
                            PublicationYear = 2004,
                            ReleaseYear = 0,
                            StudioId = 9,
                            Synopsis = "Bleach follows Ichigo Kurosaki, a teenager who can see ghosts,\r\nand Rukia Kuchiki, a Soul Reaper (Shinigami). After Rukia\r\nshares her powers with Ichigo to save his family, he must protect\r\nhumans from evil spirits called Hollows and guide lost souls.",
                            Title = "Bleach",
                            TvRating = "TV-14"
                        },
                        new
                        {
                            Id = 102,
                            Episodes = 63,
                            PublicationYear = 2016,
                            ReleaseYear = 0,
                            StudioId = 5,
                            Synopsis = "Set in Taisho Era Japan, the story follows a boy, Tanjiro Kamado,\r\nwho's family is massacred by a demon which sets him on the\r\npath for revenge. Eventually, he meets an organization called the\r\nDemon Slayer Corp who help him in this adventure.",
                            Title = "Demon Slayer",
                            TvRating = "TV-14"
                        },
                        new
                        {
                            Id = 103,
                            Episodes = 1300,
                            PublicationYear = 1997,
                            ReleaseYear = 0,
                            StudioId = 10,
                            Synopsis = "Humans known as 'Trainers' catch, train, and battle creatures\r\nknown as Pokémon. The trainers and they're Pokémon not only\r\nshare a special bond in battle, but also a deep friendship.",
                            Title = "Pokemon",
                            TvRating = "TV-PG"
                        },
                        new
                        {
                            Id = 104,
                            Episodes = 1170,
                            PublicationYear = 2004,
                            ReleaseYear = 0,
                            StudioId = 11,
                            Synopsis = "Monkey D. Luffy dreams of becoming the Pirate King by finding\r\nthe legendary \"One Piece\" treasure left behind by Gol D. Roger.\r\nAfter accidentally eating a magical Gum-Gum Devil Fruit, Luffy\r\ngained the ability to stretch like rubber. He sets sail, assembling a\r\nloyal and eccentric crew, to conquer the perilous Grand Line.",
                            Title = "One Piece",
                            TvRating = "TV-14"
                        },
                        new
                        {
                            Id = 105,
                            Episodes = 220,
                            PublicationYear = 1999,
                            ReleaseYear = 0,
                            StudioId = 9,
                            Synopsis = "Focus' on the struggle of a young ninja in the Hidden Leaf Village,\r\nNaruto Uzumaki. He faces many dangers with his companions\r\nSasuke Uchiha and Sakura Haruno, including other ninja and\r\nother villages.",
                            Title = "Naruto",
                            TvRating = "TV-PG"
                        },
                        new
                        {
                            Id = 106,
                            Episodes = 291,
                            PublicationYear = 1989,
                            ReleaseYear = 0,
                            StudioId = 11,
                            Synopsis = "Follows a hero named Goku and his friends who together, these\r\nfighters defend Earth from powerful space aliens, killer robots,\r\nand magic monsters through intense martial arts battles.",
                            Title = "Dragon Ball",
                            TvRating = "TV-PG"
                        },
                        new
                        {
                            Id = 107,
                            Episodes = 48,
                            PublicationYear = 2023,
                            ReleaseYear = 0,
                            StudioId = 10,
                            Synopsis = "Historical mystery anime following Maomao, a young apothecary\r\nsold into palace servitude, who solves medical and court\r\nmysteries using her vast knowledge of poisons and herbs.",
                            Title = "Apothecary Diaries",
                            TvRating = "TV-14"
                        },
                        new
                        {
                            Id = 108,
                            Episodes = 38,
                            PublicationYear = 2023,
                            ReleaseYear = 0,
                            StudioId = 2,
                            Synopsis = "Fantasy anime series that follows Frieren, an immortal elf mage.\r\nIt uniquely begins after her party defeats the Demon King,\r\nexploring her emotional journey to understand human mortality\r\nand connections decades later with her new party.",
                            Title = "Frieren: Beyond Journey's End",
                            TvRating = "TV-14"
                        },
                        new
                        {
                            Id = 109,
                            Episodes = 24,
                            PublicationYear = 2017,
                            ReleaseYear = 0,
                            StudioId = 3,
                            Synopsis = "Fantasy anime series that follows Chise Hatori, a young girl\r\nsold at an auction to a mysterious non-human mage named Elias\r\nAinsworth. The story explores their relationship and Chise's\r\njourney of self-discovery in a world of magic and mythical creatures.",
                            Title = "The Ancient Magus' Bride",
                            TvRating = "TV-14"
                        },
                        new
                        {
                            Id = 110,
                            Episodes = 200,
                            PublicationYear = 1992,
                            ReleaseYear = 0,
                            StudioId = 11,
                            Synopsis = "Following Usagi Tsukino, a clumsy, average teenager who\r\ndiscovers she is the reincarnation of a Moon Kingdom princess.\r\nGuided by a talking cat named Luna, she transforms into the\r\nmagical guardian \"Sailor Moon\" to fight dark forces and protect\r\nEarth alongside a team of fellow Sailor Guardians.",
                            Title = "Sailor Moon",
                            TvRating = "TV-PG"
                        },
                        new
                        {
                            Id = 111,
                            Episodes = 13,
                            PublicationYear = 2025,
                            ReleaseYear = 0,
                            Synopsis = "Follows a noble woman, Scarlet El Vandimion, who's received\r\nUnflattering nicknames due to her love for a good beatdown on\r\nunjustly nobles. Scarlet is also on mission with the Prince, Julius,\r\nto bring down corrupt nobility and religious institutions.",
                            Title = "May I Ask For One Final Thing",
                            TvRating = "TV-MA"
                        },
                        new
                        {
                            Id = 112,
                            Episodes = 12,
                            PublicationYear = 2022,
                            ReleaseYear = 0,
                            Synopsis = "Fantasy anime series that follows Menou, a skilled executioner\r\nwho is tasked with eliminating individuals summoned from\r\nanother world. The story explores themes of morality, justice,\r\nand the consequences of wielding power in a fantastical setting.",
                            Title = "The Executioner and Her Way of Life",
                            TvRating = "TV-14"
                        },
                        new
                        {
                            Id = 113,
                            Episodes = 12,
                            PublicationYear = 2021,
                            ReleaseYear = 0,
                            Synopsis = "Fantasy anime series that follows Lugh Tuatha De, a skilled\r\nassassin who is reincarnated into a parallel world. Tasked with\r\npreventing the rise of a destructive hero, Lugh must navigate\r\npolitical intrigue and moral dilemmas to fulfill his mission.",
                            Title = "The World's Finest Assassin",
                            TvRating = "TV-14"
                        });
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Anime with intense action sequences and battles.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Anime that follows characters on exciting journeys and quests.",
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Anime that focuses on humor and comedic situations.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Anime that explores emotional and dramatic storylines.",
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Anime set in fantastical worlds with magical elements.",
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Anime that aims to scare or unsettle the audience.",
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Anime that focuses on romantic relationships and love stories.",
                            Name = "Romance"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Anime that explores futuristic or scientific concepts.",
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Anime that depicts everyday life and experiences of characters.",
                            Name = "Slice of Life"
                        });
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A renowned Japanese animation studio.",
                            Name = "Studio Ghibli"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A Japanese animation studio known for its high-quality productions.",
                            Name = "Madhouse"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A Japanese animation studio known for its diverse range of anime series.",
                            Name = "Bones"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A Japanese animation studio known for its detailed animation and character-driven stories.",
                            Name = "Kyoto Animation"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A Japanese animation studio known for its visually stunning anime adaptations.",
                            Name = "Ufotable"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A Japanese animation studio known for its mecha and science fiction anime.",
                            Name = "Sunrise"
                        },
                        new
                        {
                            Id = 7,
                            Description = "A Japanese animation studio known for its creative and innovative approach to anime production.",
                            Name = "Wit Studio"
                        },
                        new
                        {
                            Id = 8,
                            Description = "A Japanese animation studio known for its high-quality productions and attention to detail.",
                            Name = "Studio Deen"
                        },
                        new
                        {
                            Id = 9,
                            Description = "A Japanese animation studio known for its long-running anime series and adaptations of popular manga.",
                            Name = "Pierrot"
                        },
                        new
                        {
                            Id = 10,
                            Description = "A Japanese animation studio known for its iconic anime series and films.",
                            Name = "OLM"
                        },
                        new
                        {
                            Id = 11,
                            Description = "A Japanese animation studio known for its long-running anime series and adaptations of popular manga.",
                            Name = "Toei Animation"
                        });
                });

            modelBuilder.Entity("AnimeGenre", b =>
                {
                    b.HasOne("TeamPiZAZCPW211TeamProject.Models.Anime", null)
                        .WithMany()
                        .HasForeignKey("AnimesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamPiZAZCPW211TeamProject.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Anime", b =>
                {
                    b.HasOne("TeamPiZAZCPW211TeamProject.Models.Studio", "Studio")
                        .WithMany("Animes")
                        .HasForeignKey("StudioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("TeamPiZAZCPW211TeamProject.Models.Studio", b =>
                {
                    b.Navigation("Animes");
                });
#pragma warning restore 612, 618
        }
    }
}
